# Generated by Django 5.0.6 on 2024-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('specialite', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
    ]
